# -*- coding: utf-8 -*-
"""app.py3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qi85tv0d0xZQB-e6h9b_aXgYgo7uJxO7
"""

import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Load dataset
df = pd.read_csv("spam.csv", encoding="latin-1")

# Keep only required columns
df = df[['v1', 'v2']]
df.columns = ['label', 'message']

# Convert labels
df['label'] = df['label'].map({'ham':0,'spam':1})

# Features and target
X = df['message']
y = df['label']

# Convert text into numbers
vectorizer = CountVectorizer()

X = vectorizer.fit_transform(X)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train model
model = MultinomialNB()

model.fit(X_train, y_train)

# Accuracy
predictions = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test,predictions))

# Save files
joblib.dump(model,"spam_model.pkl")
joblib.dump(vectorizer,"vectorizer.pkl")

print("Model Saved Successfully!")









import streamlit as st

model = joblib.load("spam_model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

st.title("📧 Email Spam Detection")

message = st.text_area("Enter Email or SMS")

if st.button("Predict"):

    if message.strip() == "":
        st.warning("Please enter a message.")
    else:

        vector = vectorizer.transform([message])

        prediction = model.predict(vector)[0]

        if prediction == 1:
            st.error("🚨 Spam Message")
        else:
            st.success("✅ Not Spam")

